import type { Request, Response } from "express";
import { Router } from "express";
import { storage } from "./storage";
import { applyPiiMasking, canViewUnmasked } from "./masking";
import { toCsv } from "./csv";
import {
  type AuthRequest,
  requireAuth,
  requireActiveSubscription,
  getClientIp,
} from "./auth";

async function renderClaimPdf(args: {
  exportType: "intelligence_summary" | "claim_packet_masked" | "claim_packet_unmasked";
  claim: any;
  supplements: any[];
  generatedBy: { userId: string; role: string; tenantId: string };
}): Promise<Buffer> {
  const lines: string[] = [];

  lines.push("ClaimSignal™ Export");
  lines.push(`Export Type: ${args.exportType.toUpperCase()}`);
  lines.push(`Generated By User: ${args.generatedBy.userId}`);
  lines.push(`Generated At: ${new Date().toISOString()}`);
  lines.push(`Workspace: ${args.generatedBy.tenantId}`);
  lines.push("");

  lines.push(`Claim ID: ${args.claim.id}`);
  lines.push(`Claim Number: ${args.claim.claimNumber ?? ""}`);
  lines.push(`Status: ${args.claim.status ?? ""}`);
  lines.push(`Friction Score: ${args.claim.frictionScore ?? ""}`);
  lines.push(`Escalation Category: ${args.claim.escalationCategory ?? ""}`);
  lines.push(`Approval Probability: ${args.claim.approvalProbability ?? ""}`);
  lines.push("");

  if (args.exportType !== "intelligence_summary") {
    lines.push(`Homeowner Name: ${args.claim.homeownerName ?? ""}`);
    lines.push(`Property Address: ${args.claim.propertyAddress ?? ""}`);
    lines.push(`Claim Number: ${args.claim.claimNumber ?? ""}`);
    lines.push(`Policy Number: ${args.claim.policyNumber ?? ""}`);
    lines.push(`Phone: ${args.claim.homeownerPhone ?? ""}`);
    lines.push(`Email: ${args.claim.homeownerEmail ?? ""}`);
    lines.push("");
  }

  if (args.supplements.length > 0) {
    lines.push("--- Supplements ---");
    for (const s of args.supplements) {
      lines.push(
        `  Submitted: ${s.dateSubmitted ?? ""} | Requested: $${s.amountRequested ?? 0} | Approved: $${s.amountApproved ?? 0} | Status: ${s.status ?? ""}`
      );
    }
    lines.push("");
  }

  if (args.exportType === "claim_packet_unmasked") {
    lines.push("*** Contains PII ***");
  }

  lines.push("---");
  lines.push(`ClaimSignal™ Export | Generated on ${new Date().toISOString()} | Export Type: ${args.exportType.toUpperCase()}`);

  return Buffer.from(lines.join("\n"), "utf8");
}

const router = Router();

router.get("/exports/claims/:claimId", requireAuth, requireActiveSubscription, async (req: AuthRequest, res: Response) => {
  try {
    const role = req.auth!.role;
    const orgId = req.auth!.organizationId;
    const claimId = req.params.claimId as string;

    const format = (req.query.format as string) === "csv" ? "csv" : "pdf";
    const exportTypeRaw = (req.query.type as string) || "claim_packet_masked";

    const exportType =
      exportTypeRaw === "intelligence_summary"
        ? "intelligence_summary"
        : exportTypeRaw === "claim_packet_unmasked"
          ? "claim_packet_unmasked"
          : "claim_packet_masked";

    const unmaskedRequested = exportType === "claim_packet_unmasked";
    const privileged = canViewUnmasked(role);

    const effectiveExportType: "intelligence_summary" | "claim_packet_masked" | "claim_packet_unmasked" =
      unmaskedRequested && privileged ? "claim_packet_unmasked" : exportType === "intelligence_summary" ? "intelligence_summary" : "claim_packet_masked";

    let claim = role === "super_admin"
      ? await storage.getClaim(claimId, orgId) || (await storage.getAllClaimsAcrossTenants()).find(c => c.id === claimId)
      : await storage.getClaim(claimId, orgId);

    if (!claim) return res.status(404).json({ message: "Claim not found" });

    const supps = await storage.getSupplements(claimId, claim.organizationId);

    let merged: any = { ...claim };

    if (effectiveExportType === "claim_packet_masked") {
      merged = applyPiiMasking(merged, role);
    } else if (effectiveExportType === "intelligence_summary") {
      merged.homeownerName = undefined;
      merged.homeownerPhone = undefined;
      merged.homeownerEmail = undefined;
      merged.propertyAddress = undefined;
      merged.claimNumber = undefined;
      merged.policyNumber = undefined;
      merged.insuredName = undefined;
    }

    await storage.createAuditLog({
      organizationId: claim.organizationId,
      actorUserId: req.auth!.userId,
      actorRole: role,
      actionType: effectiveExportType === "claim_packet_unmasked" ? "EXPORT_UNMASKED" : "EXPORT_MASKED",
      entityType: "claim",
      entityId: claimId,
      afterJson: { format, exportType: effectiveExportType },
      ipAddress: getClientIp(req),
    });

    if (format === "csv") {
      const columns =
        effectiveExportType === "intelligence_summary"
          ? [
              { key: "id", label: "Claim ID" },
              { key: "status", label: "Status" },
              { key: "frictionScore", label: "Friction Score" },
              { key: "escalationCategory", label: "Escalation Category" },
              { key: "approvalProbability", label: "Approval Probability" },
              { key: "rcvTotal", label: "RCV Total" },
              { key: "acvTotal", label: "ACV Total" },
            ]
          : [
              { key: "id", label: "Claim ID" },
              { key: "homeownerName", label: "Homeowner" },
              { key: "propertyAddress", label: "Address" },
              { key: "claimNumber", label: "Claim Number" },
              { key: "policyNumber", label: "Policy Number" },
              { key: "status", label: "Status" },
              { key: "frictionScore", label: "Friction Score" },
              { key: "escalationCategory", label: "Escalation Category" },
              { key: "approvalProbability", label: "Approval Probability" },
              { key: "rcvTotal", label: "RCV Total" },
              { key: "acvTotal", label: "ACV Total" },
            ];

      const csv = toCsv([merged], columns);
      res.setHeader("Content-Type", "text/csv; charset=utf-8");
      res.setHeader("Content-Disposition", `attachment; filename="claim_${claimId}_${effectiveExportType}.csv"`);
      return res.status(200).send(csv);
    }

    const pdfBytes = await renderClaimPdf({
      exportType: effectiveExportType,
      claim: merged,
      supplements: supps,
      generatedBy: { userId: req.auth!.userId, role, tenantId: orgId },
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="claim_${claimId}_${effectiveExportType}.pdf"`);
    return res.status(200).send(pdfBytes);
  } catch (e: any) {
    return res.status(500).json({ message: "Export error: " + e.message });
  }
});

export default router;
