import { storage } from "./storage";
import type { InsertPlaybookEntry } from "@shared/schema";

/**
 * Seeds sample Playbook entries using GENERIC / masked data (no real homeowner
 * or contractor identity). Idempotent: skips entries whose title already exists.
 * Gated by the same demo-seeding policy used elsewhere.
 */
const SAMPLE_PLAYBOOKS: InsertPlaybookEntry[] = [
  {
    title: "Denial Overturned After Reinspection",
    scenarioType: "denial_overturned",
    claimType: "Hail / Wind",
    carrier: "State Farm",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Independent Adjusting Firm",
    vendor: "EagleView",
    denialReason: "Wear and tear / cosmetic",
    missingScopeItems: ["test square documentation", "matching shingle availability"],
    documentationUsed: ["dated photo report", "ITEL match report", "manufacturer brittleness bulletin"],
    actionTaken: "Requested reinspection with documented hail hits per slope and submitted code/manufacturer references.",
    whatWorked: "Per-slope test squares + manufacturer documentation removed the cosmetic argument.",
    whatDidNotWork: "Initial phone-only appeal without new evidence was ignored.",
    timelineSummary: "Denial → reinspection requested (7 days) → reinspection (21 days) → approval.",
    escalationUsed: false,
    outcome: "Full approval",
    supplementDelta: 8200,
    confidenceScore: 0.82,
    sourceClaimCount: 4,
    region: "TX",
    recommendedNextStep: "Request reinspection with per-slope test squares and manufacturer brittleness reference.",
    isSample: true,
  },
  {
    title: "Missing Drip Edge and Starter Recovered",
    scenarioType: "missing_scope_recovered",
    claimType: "Hail",
    carrier: "Allstate",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "Ladder assist company",
    denialReason: "Items not included in original scope",
    missingScopeItems: ["drip edge", "starter course", "ridge vent"],
    documentationUsed: ["IRC R905.2.8.5 reference", "local code amendment", "photos of existing components"],
    actionTaken: "Submitted line-item supplement citing IRC + local code requiring drip edge and starter.",
    whatWorked: "Code citations tied to existing-condition photos forced inclusion.",
    whatDidNotWork: "Generic 'industry standard' language alone was rejected.",
    timelineSummary: "Initial estimate → supplement submitted (10 days) → partial approval → full inclusion after code letter.",
    escalationUsed: false,
    outcome: "Supplement approved",
    supplementDelta: 1450,
    confidenceScore: 0.78,
    sourceClaimCount: 6,
    region: "Southeast",
    recommendedNextStep: "Attach IRC R905 + local amendment with existing-condition photos to the supplement.",
    isSample: true,
  },
  {
    title: "Vendor Report Challenged Successfully",
    scenarioType: "vendor_report_challenged",
    claimType: "Wind",
    carrier: "Travelers",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Independent Adjusting Firm",
    vendor: "Engineering firm",
    denialReason: "Engineering report attributed damage to age",
    missingScopeItems: ["wind directionality analysis", "comparable storm data"],
    documentationUsed: ["NOAA storm report", "counter-engineering opinion", "dated pre-loss imagery"],
    actionTaken: "Submitted rebuttal with NOAA verified wind event and counter-engineering review.",
    whatWorked: "Independent storm verification contradicted the vendor's age conclusion.",
    whatDidNotWork: "Disputing the report without a competing expert opinion stalled.",
    timelineSummary: "Engineering denial → rebuttal packet (14 days) → reinspection → approval.",
    escalationUsed: true,
    outcome: "Denial overturned",
    supplementDelta: 15600,
    confidenceScore: 0.74,
    sourceClaimCount: 3,
    region: "Midwest",
    recommendedNextStep: "Pair NOAA storm verification with an independent engineering rebuttal before reinspection.",
    isSample: true,
  },
  {
    title: "Supplement Approved After Documentation Pressure",
    scenarioType: "supplement_approved",
    claimType: "Hail / Wind",
    carrier: "Farmers",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "SeekNow",
    denialReason: "Insufficient documentation",
    missingScopeItems: ["detached structures", "gutters", "screens"],
    documentationUsed: ["annotated photo report", "Xactimate line items", "scope narrative"],
    actionTaken: "Resubmitted with annotated photos mapped to each line item and a written scope narrative.",
    whatWorked: "One-to-one photo-to-line-item mapping eliminated 'insufficient documentation'.",
    whatDidNotWork: "Bulk photo dumps without annotation were repeatedly returned.",
    timelineSummary: "Supplement returned → annotated resubmission (5 days) → approval.",
    escalationUsed: false,
    outcome: "Supplement approved",
    supplementDelta: 3900,
    confidenceScore: 0.8,
    sourceClaimCount: 5,
    region: "TX",
    recommendedNextStep: "Map every photo to a specific Xactimate line item and include a scope narrative.",
    isSample: true,
  },
  // ── Expanded library: USAA ─────────────────────────────────────────────────
  {
    title: "USAA Wind Claim Reversed After NOAA Verification",
    scenarioType: "denial_overturned",
    claimType: "Wind",
    carrier: "USAA",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Independent Adjusting Firm",
    vendor: "CoreLogic",
    denialReason: "Wind speed insufficient to cause damage",
    missingScopeItems: ["NOAA storm data", "wind speed certification", "directional damage analysis"],
    documentationUsed: ["NOAA certified wind event report", "storm damage photos with date/time metadata", "neighboring property damage records"],
    actionTaken: "Pulled NOAA-certified storm data showing gusts >60 mph and submitted alongside directional damage photos.",
    whatWorked: "NOAA certification is difficult for USAA adjusters to dispute — wind speed was on record.",
    whatDidNotWork: "Verbal dispute without third-party data was dismissed at first contact.",
    timelineSummary: "Initial denial → NOAA report submitted (5 days) → reinspection scheduled (14 days) → approval.",
    escalationUsed: false,
    outcome: "Full approval",
    supplementDelta: 11200,
    confidenceScore: 0.85,
    sourceClaimCount: 5,
    region: "Southeast",
    recommendedNextStep: "Pull NOAA-certified wind event report immediately and attach to initial supplement package.",
    isSample: true,
  },
  {
    title: "USAA Hail Claim Approved via Brittle Test Documentation",
    scenarioType: "denial_overturned",
    claimType: "Hail",
    carrier: "USAA",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "EagleView",
    denialReason: "Damage attributed to pre-existing brittleness, not storm",
    missingScopeItems: ["brittle test documentation", "manufacturer age certification", "hail size verification"],
    documentationUsed: ["certified brittle test squares", "manufacturer material age bulletin", "NOAA hail size report"],
    actionTaken: "Performed standardized brittle tests per manufacturer protocol, documented with calibrated measurements, submitted alongside hail size certification.",
    whatWorked: "Manufacturer protocol brittle testing provided objective standard — adjuster could not dispute methodology.",
    whatDidNotWork: "Arguing brittleness without testing data was rejected as subjective.",
    timelineSummary: "Cosmetic-only determination → brittle test results submitted (8 days) → full scope approval.",
    escalationUsed: false,
    outcome: "Full approval",
    supplementDelta: 7800,
    confidenceScore: 0.79,
    sourceClaimCount: 4,
    region: "TX",
    recommendedNextStep: "Perform manufacturer-protocol brittle tests before reinspection; include test square photos with calibration.",
    isSample: true,
  },
  // ── State Farm ─────────────────────────────────────────────────────────────
  {
    title: "State Farm Water Damage — ACV Upgraded to RCV After Code Dispute",
    scenarioType: "supplement_approved",
    claimType: "Water",
    carrier: "State Farm",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "Contractor estimate",
    denialReason: "Depreciation held — ACV only, RCV withheld",
    missingScopeItems: ["code upgrade documentation", "permit requirement letter", "replacement-vs-repair analysis"],
    documentationUsed: ["local building department code letter", "contractor permit estimate", "IRC section references"],
    actionTaken: "Obtained written confirmation from local building department that full replacement was code-required, not optional.",
    whatWorked: "Official code compliance letter from municipality converted ACV to RCV settlement — carrier had no counterargument.",
    whatDidNotWork: "Contractor-only argument that replacement was 'required' without official documentation was insufficient.",
    timelineSummary: "ACV offer → code letter obtained (10 days) → supplement submitted → RCV released (7 days).",
    escalationUsed: false,
    outcome: "RCV released in full",
    supplementDelta: 9400,
    confidenceScore: 0.83,
    sourceClaimCount: 7,
    region: "Midwest",
    recommendedNextStep: "Obtain written code compliance letter from local building department before supplement submission.",
    isSample: true,
  },
  {
    title: "State Farm Fire Claim Scope Expanded via Public Adjuster",
    scenarioType: "missing_scope_recovered",
    claimType: "Fire",
    carrier: "State Farm",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Public Adjusting Firm",
    vendor: "Restoration contractor",
    denialReason: "Smoke damage to unaffected rooms excluded",
    missingScopeItems: ["smoke penetration testing", "HVAC system contamination", "contents inventory"],
    documentationUsed: ["third-party air quality test", "HVAC contractor assessment", "contents inventory with replacement values"],
    actionTaken: "Public adjuster re-scoped with industrial hygienist report on smoke infiltration and HVAC contamination findings.",
    whatWorked: "Third-party industrial hygienist report established smoke migration as a fact, not an interpretation.",
    whatDidNotWork: "Contractor estimates alone for hidden damage were dismissed without independent testing.",
    timelineSummary: "Initial scope issued → PA engaged → hygienist report (14 days) → expanded scope approved.",
    escalationUsed: false,
    outcome: "Expanded scope approved",
    supplementDelta: 22000,
    confidenceScore: 0.77,
    sourceClaimCount: 3,
    region: "Southeast",
    recommendedNextStep: "Engage industrial hygienist for smoke infiltration report before scope negotiation with State Farm.",
    isSample: true,
  },
  // ── Allstate ───────────────────────────────────────────────────────────────
  {
    title: "Allstate Hail Denial Overturned via Appraisal Clause",
    scenarioType: "denial_overturned",
    claimType: "Hail",
    carrier: "Allstate",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Independent Adjusting Firm",
    vendor: "EagleView",
    denialReason: "Hail damage below deductible / cosmetic only",
    missingScopeItems: ["appraisal clause invocation", "umpire selection", "independent IA estimate"],
    documentationUsed: ["policy appraisal clause reference", "independent IA estimate", "storm report", "signed umpire agreement"],
    actionTaken: "Invoked appraisal clause after Allstate's second inspection maintained cosmetic-only position. Hired IA; umpire found functional damage.",
    whatWorked: "Appraisal process removed subjective carrier interpretation — umpire decision was binding.",
    whatDidNotWork: "Multiple rounds of direct negotiation with desk adjuster produced no movement without appraisal threat.",
    timelineSummary: "Second denial → appraisal invoked → umpire selected (21 days) → award issued.",
    escalationUsed: true,
    outcome: "Appraisal award issued",
    supplementDelta: 14500,
    confidenceScore: 0.81,
    sourceClaimCount: 4,
    region: "TX",
    recommendedNextStep: "Review policy for appraisal clause before second reinspection — invoke early if carrier maintains cosmetic-only position.",
    isSample: true,
  },
  // ── Travelers ──────────────────────────────────────────────────────────────
  {
    title: "Travelers Water Claim — Matching Dispute Resolved via Discontinued Product Letter",
    scenarioType: "supplement_approved",
    claimType: "Water",
    carrier: "Travelers",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "Flooring contractor",
    denialReason: "Matching dispute — carrier refused to replace undamaged adjacent flooring",
    missingScopeItems: ["discontinued product letter", "matching floor sample search documentation", "state matching law citation"],
    documentationUsed: ["manufacturer discontinued product confirmation", "3 flooring supplier unavailability letters", "state insurance code matching section"],
    actionTaken: "Documented product discontinuation with manufacturer letter and cited state insurance code on matching obligation.",
    whatWorked: "State law citation combined with documented unavailability created legal obligation — Travelers approved full floor.",
    whatDidNotWork: "Aesthetic argument alone was rejected; Travelers required documented proof of unavailability.",
    timelineSummary: "Partial approval (damaged section only) → matching documentation submitted → full floor approved.",
    escalationUsed: false,
    outcome: "Full matching replacement approved",
    supplementDelta: 8700,
    confidenceScore: 0.76,
    sourceClaimCount: 5,
    region: "Southeast",
    recommendedNextStep: "Document product discontinuation with manufacturer letter and cite applicable state matching law in supplement.",
    isSample: true,
  },
  {
    title: "Travelers Engineering Denial Challenged via Independent Expert",
    scenarioType: "vendor_report_challenged",
    claimType: "Wind",
    carrier: "Travelers",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Independent Adjusting Firm",
    vendor: "Engineering firm",
    denialReason: "Independent engineering report: damage pre-existing",
    missingScopeItems: ["counter-engineering report", "NOAA storm certification", "pre-loss drone imagery"],
    documentationUsed: ["independent structural engineering rebuttal", "NOAA event certification", "pre-loss Google Earth imagery showing intact structure"],
    actionTaken: "Commissioned counter-engineering report; used pre-loss satellite imagery to establish structure was undamaged before the storm.",
    whatWorked: "Pre-loss imagery is objective and time-stamped — effectively proved damage did not pre-exist the storm event.",
    whatDidNotWork: "Contractor affidavit alone claiming storm causation was insufficient against engineering opinion.",
    timelineSummary: "Engineering denial → counter-report commissioned (21 days) → pre-loss imagery obtained → approval.",
    escalationUsed: true,
    outcome: "Denial overturned",
    supplementDelta: 19800,
    confidenceScore: 0.73,
    sourceClaimCount: 3,
    region: "Midwest",
    recommendedNextStep: "Obtain pre-loss satellite/drone imagery before commissioning counter-engineering report.",
    isSample: true,
  },
  // ── Liberty Mutual ─────────────────────────────────────────────────────────
  {
    title: "Liberty Mutual Hail — Supplement Won After IRC Code Letter",
    scenarioType: "supplement_approved",
    claimType: "Hail",
    carrier: "Liberty Mutual",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "Roofing contractor",
    denialReason: "Code upgrades not covered / excluded",
    missingScopeItems: ["IRC code upgrade documentation", "local permit requirement", "ACV vs RCV policy review"],
    documentationUsed: ["IRC R905.1.1 reference letter", "local building department written requirement", "policy declaration page coverage review"],
    actionTaken: "Submitted IRC code letter citing required ice and water shield upgrade per current code, backed by local building department written confirmation.",
    whatWorked: "Two-layer documentation (IRC + local municipality) made exclusion argument untenable.",
    whatDidNotWork: "Citing code without local confirmation was initially refused as 'local codes may vary'.",
    timelineSummary: "Code upgrade denial → IRC letter + local confirmation submitted → approved within 10 days.",
    escalationUsed: false,
    outcome: "Code upgrades approved",
    supplementDelta: 4200,
    confidenceScore: 0.82,
    sourceClaimCount: 6,
    region: "Midwest",
    recommendedNextStep: "Submit IRC code section reference alongside local building department written confirmation — never cite IRC alone.",
    isSample: true,
  },
  {
    title: "Liberty Mutual Water — RCV Released After Contractor Start Notice",
    scenarioType: "supplement_approved",
    claimType: "Water",
    carrier: "Liberty Mutual",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "Water mitigation company",
    denialReason: "RCV withheld pending repairs completion",
    missingScopeItems: ["signed contractor agreement", "work commencement documentation", "completion timeline"],
    documentationUsed: ["signed contractor agreement with start date", "permit pulled confirmation", "material delivery receipts"],
    actionTaken: "Provided signed contractor agreement with firm start date and submitted permit confirmation as proof repairs commenced.",
    whatWorked: "Policy RCV holdback provision required repair commencement — permits and signed agreement satisfied the condition.",
    whatDidNotWork: "Verbal confirmation repairs would begin was not accepted; carrier required documented proof.",
    timelineSummary: "ACV only → signed contract + permit submitted → RCV released (7 days).",
    escalationUsed: false,
    outcome: "RCV released",
    supplementDelta: 12300,
    confidenceScore: 0.84,
    sourceClaimCount: 8,
    region: "Southeast",
    recommendedNextStep: "Pull permit and get signed contractor agreement before requesting RCV release from Liberty Mutual.",
    isSample: true,
  },
  // ── Farmers ────────────────────────────────────────────────────────────────
  {
    title: "Farmers Wind — Scope Dispute Resolved via Re-Inspection with PA",
    scenarioType: "denial_overturned",
    claimType: "Wind",
    carrier: "Farmers",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Public Adjusting Firm",
    vendor: "Roofing contractor",
    denialReason: "Field adjuster scope significantly lower than contractor estimate",
    missingScopeItems: ["third-party field measurement", "wind damage documentation protocol", "slope-by-slope photo analysis"],
    documentationUsed: ["public adjuster re-scope with Xactimate", "slope-by-slope photo documentation", "contractor signed damage assessment"],
    actionTaken: "PA conducted independent re-scope with Xactimate; identified 12 missed line items including detached structure and decking.",
    whatWorked: "PA Xactimate re-scope alongside contractor findings created two independent estimates — Farmers negotiated to middle ground well above original.",
    whatDidNotWork: "Submitting contractor estimate alone as proof of scope gap was dismissed as self-serving.",
    timelineSummary: "Low scope issued → PA engaged (5 days) → re-scope submitted → negotiated settlement.",
    escalationUsed: false,
    outcome: "Negotiated settlement — 71% of contractor estimate",
    supplementDelta: 16400,
    confidenceScore: 0.75,
    sourceClaimCount: 4,
    region: "TX",
    recommendedNextStep: "Engage PA for independent Xactimate re-scope; two independent estimates give leverage in negotiation.",
    isSample: true,
  },
  {
    title: "Farmers Fire — DOI Complaint Triggered Prompt Settlement",
    scenarioType: "denial_overturned",
    claimType: "Fire",
    carrier: "Farmers",
    adjuster: "Field Adjuster (anonymized)",
    iaFirm: "Public Adjusting Firm",
    vendor: "Restoration contractor",
    denialReason: "Delayed claim processing — beyond statutory timeframe",
    missingScopeItems: ["DOI complaint documentation", "statutory timeline reference", "claims handling violation letter"],
    documentationUsed: ["state DOI complaint submission", "certified statutory timeline letter", "claims handling violation documentation"],
    actionTaken: "After 90+ days with no resolution, filed DOI complaint citing state claims handling statute on timeline requirements.",
    whatWorked: "DOI complaint created regulatory pressure — Farmers assigned senior adjuster and issued settlement within 30 days.",
    whatDidNotWork: "Multiple escalation calls and supervisor requests produced temporary attention but no resolution.",
    timelineSummary: "Claim filed → 90 days stalled → DOI complaint filed → senior adjuster assigned (7 days) → settlement issued (30 days).",
    escalationUsed: true,
    outcome: "Settlement issued after DOI intervention",
    supplementDelta: 28500,
    confidenceScore: 0.78,
    sourceClaimCount: 3,
    region: "Southeast",
    recommendedNextStep: "If claim exceeds state statutory timeline, file DOI complaint with timeline documentation — it creates enforceable pressure.",
    isSample: true,
  },
  // ── Generic high-value scenarios ───────────────────────────────────────────
  {
    title: "Matching Dispute Won Under State Insurance Code",
    scenarioType: "supplement_approved",
    claimType: "Hail / Wind",
    carrier: "Multiple",
    adjuster: "Desk Adjuster (anonymized)",
    iaFirm: null,
    vendor: "Roofing contractor",
    denialReason: "Carrier refused to replace undamaged sections for uniformity",
    missingScopeItems: ["state matching law citation", "discontinued product certification", "aesthetics impact documentation"],
    documentationUsed: ["state insurance code matching statute", "manufacturer discontinuation letter", "before/after property photos"],
    actionTaken: "Cited applicable state insurance code section on matching obligation; provided manufacturer letter confirming discontinuation.",
    whatWorked: "State law citation created legal obligation that adjuster could not override — carrier capitulated to avoid regulatory exposure.",
    whatDidNotWork: "Aesthetic argument without legal foundation was consistently refused.",
    timelineSummary: "Partial approval → state law letter submitted → full replacement approved.",
    escalationUsed: false,
    outcome: "Full matching replacement approved",
    supplementDelta: 6800,
    confidenceScore: 0.80,
    sourceClaimCount: 9,
    region: "Multiple",
    recommendedNextStep: "Research your state's matching statute and cite the specific code section in the supplement letter.",
    isSample: true,
  },
];

export async function seedSamplePlaybooks(): Promise<number> {
  const existing = await storage.getPlaybookEntries();
  const existingTitles = new Set(existing.map((e) => e.title));
  let created = 0;
  for (const pb of SAMPLE_PLAYBOOKS) {
    if (existingTitles.has(pb.title)) continue;
    await storage.createPlaybookEntry(pb);
    created++;
  }
  return created;
}
